# -*- coding: utf-8 -*-
"""RLS_time_varying_channel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bTjknFeXT_0lxuc4GEW6r70Gw5V77R0h
"""

import numpy as np
import matplotlib.pyplot as plt

num_bits = 10000

sps = 3
beta = 0.25
span = 10


num_taps = 4
my_snr =8

training_len = 2000
testing_len = 4000

Nf = 11
Nb = 5
delta = 1.0
lam = 0.995
mu_b = 0.001
dd_start_offset = 1000

snr_db_range = np.arange(0, 21, 2)


f_d = 10
block_size=500

# Generate random bits
def bit_generation(num_bits):
    return np.random.randint(0, 2, num_bits)

bits = bit_generation(num_bits)

print(bits[:20])

def bit_pairs(bits):
    return bits.reshape(-1, 2)

bit_pairs = bit_pairs(bits)
print(bit_pairs[:20])

# QPSK mapping (Gray-coded)
def qpsk_modulation(bit_pairs):
    mapping = {
        (0, 0): (1 + 1j) / np.sqrt(2),
        (0, 1): (-1 + 1j) / np.sqrt(2),
        (1, 1): (-1 - 1j) / np.sqrt(2),
        (1, 0): (1 - 1j) / np.sqrt(2),
    }
    return np.array([mapping[tuple(bp)] for bp in bit_pairs])
qpsk_symbols = qpsk_modulation(bit_pairs)
print(qpsk_symbols[:20])

# Upsampling
def upsample(signal, sps):
    upsampled = np.zeros(len(signal) * sps, dtype=complex)
    upsampled[::sps] = signal
    return upsampled

upsampled = upsample(qpsk_symbols, sps)
print(upsampled[:20])

# RRC filter design
def rrc_filter(beta, sps, span):
    N = span * sps
    t = np.arange(-N // 2, N // 2 + 1) / sps
    h = np.zeros_like(t)
    for i in range(len(t)):
        if t[i] == 0.0:
            h[i] = 1.0 - beta + (4 * beta / np.pi)
        elif abs(t[i]) == 1 / (4 * beta):
            h[i] = (beta / np.sqrt(2)) * (
                ((1 + 2 / np.pi) * np.sin(np.pi / (4 * beta))) +
                ((1 - 2 / np.pi) * np.cos(np.pi / (4 * beta)))
            )
        else:
            numerator = np.sin(np.pi * t[i] * (1 - beta)) + \
                        4 * beta * t[i] * np.cos(np.pi * t[i] * (1 + beta))
            denominator = np.pi * t[i] * (1 - (4 * beta * t[i]) ** 2)
            h[i] = numerator / denominator
    return h / np.sqrt(np.sum(h**2))


rrc = rrc_filter(beta, sps, span)

# Filtered transmit signal
tx_signal = np.convolve(upsampled, rrc, mode='same')

# Calculate delay from filter length
delay = (len(rrc) - 1) // 2

# Symbol-rate sampling (to observe clean constellation)
sampled_tx = tx_signal[delay::sps]

# Plot symbol-rate constellation
plt.figure(figsize=(5, 5))
plt.plot(np.real(sampled_tx), np.imag(sampled_tx), 'bo')
plt.title("Sampled RRC Output (Symbol Rate)")
plt.xlabel("In-phase")
plt.ylabel("Quadrature")
plt.grid(True)
plt.axis("equal")
plt.show()

# Time-varying channel models
def time_varying_channel_1(length):
    """Slow fading channel with smooth variations"""
    taps = np.zeros((length, num_taps), dtype=complex)
    time = np.linspace(0, 2*np.pi, length)

    # Base taps with time-varying amplitudes and phases
    taps[:, 0] = (0.8 + 0.1*np.sin(0.1*time)) * np.exp(1j*(0.5 + 0.2*np.cos(0.05*time)))
    taps[:, 1] = (0.6 + 0.1*np.cos(0.15*time)) * np.exp(1j*(0.3 + 0.1*np.sin(0.07*time)))
    taps[:, 2] = (0.4 + 0.05*np.sin(0.2*time)) * np.exp(1j*(0.1 + 0.05*np.cos(0.1*time)))
    taps[:, 3] = (0.2 + 0.05*np.cos(0.25*time)) * np.exp(1j*(-0.1 + 0.03*np.sin(0.12*time)))

    # Normalize power
    for i in range(length):
        taps[i] /= np.sqrt(np.sum(np.abs(taps[i])**2))

    return taps

def time_varying_channel_2(length):
    """Fast fading channel with more rapid variations"""
    taps = np.zeros((length, num_taps), dtype=complex)
    time = np.linspace(0, 10*np.pi, length)

    # More rapid variations
    taps[:, 0] = (0.7 + 0.2*np.sin(0.5*time)) * np.exp(1j*(0.5 + 0.3*np.cos(0.3*time)))
    taps[:, 1] = (0.5 + 0.2*np.cos(0.6*time)) * np.exp(1j*(0.3 + 0.2*np.sin(0.4*time)))
    taps[:, 2] = (0.3 + 0.1*np.sin(0.7*time)) * np.exp(1j*(0.1 + 0.1*np.cos(0.5*time)))
    taps[:, 3] = (0.2 + 0.1*np.cos(0.8*time)) * np.exp(1j*(-0.1 + 0.1*np.sin(0.6*time)))

    # Normalize power
    for i in range(length):
        taps[i] /= np.sqrt(np.sum(np.abs(taps[i])**2))

    return taps

# jakes_fading_channel

def jakes_fading_channel(length):
    """f_d: normalized Doppler frequency (e.g., 0.01–0.1)"""
    t = np.arange(length)
    taps = np.zeros((length, num_taps), dtype=complex)
    for k in range(num_taps):
        # Independent Rayleigh fading per tap
        re = np.cos(2 * np.pi * f_d * t + 2 * np.pi * np.random.rand())
        im = np.sin(2 * np.pi * f_d * t + 2 * np.pi * np.random.rand())
        fading = (re + 1j * im) / np.sqrt(2)
        taps[:, k] = fading * (1.0 / (k + 1))  # decaying power
    # Normalize
    for i in range(length):
        taps[i] /= np.linalg.norm(taps[i])
    return taps

# Generate time-varying channels
channel_length = len(tx_signal)
tv_channel1 = time_varying_channel_1(channel_length)
tv_channel2 = time_varying_channel_2(channel_length)
tv_channel3 = jakes_fading_channel(channel_length)

# QPSK decision and bit mapping
def qpsk_decision(symbol):
    real = 1 if symbol.real >= 0 else -1
    imag = 1 if symbol.imag >= 0 else -1
    if real == 1 and imag == 1:
        return (1 + 1j) / np.sqrt(2)     # (0, 0)
    elif real == -1 and imag == 1:
        return (-1 + 1j) / np.sqrt(2)    # (0, 1)
    elif real == -1 and imag == -1:
        return (-1 - 1j) / np.sqrt(2)    # (1, 1)
    else:
        return (1 - 1j) / np.sqrt(2)     # (1, 0)

def qpsk_to_bits(symbol):
    bits = []
    for s in symbol:
        bits.append(0 if s.real >= 0 else 1)
        bits.append(0 if s.imag >= 0 else 1)
    return np.array(bits)

# Modified RLS-DFE for time-varying channels
def rls_dfe_time_varying(rx_symbols, transmitted_symbols, Nf, Nb, delta, lam, mu_b,
                         training_len, dd_start_offset, channel_variation_factor=0.001):
    N = len(rx_symbols)
    w_f = np.zeros(Nf, dtype=complex)
    w_b = np.zeros(Nb, dtype=complex)
    P_f = np.eye(Nf, dtype=complex) / delta

    x_f = np.zeros(Nf, dtype=complex)
    x_b = np.zeros(Nb, dtype=complex)
    y_out = np.zeros(N, dtype=complex)
    detected = np.zeros(N, dtype=complex)
    error_mse = np.zeros(N)
    w_f_history = np.zeros((N, Nf), dtype=complex)
    w_b_history = np.zeros((N, Nb), dtype=complex)

    for n in range(N):
        # Feedforward input
        x_f = np.roll(x_f, 1)
        x_f[0] = rx_symbols[n]

        # Feedback input
        if n == 0:
            x_b[:] = 0
        else:
            x_b = np.roll(x_b, 1)
            x_b[0] = detected[n - 1]

        # Equalizer output
        y = np.dot(w_f.conj(), x_f) - np.dot(w_b.conj(), x_b)
        y_out[n] = y

        # Define reference symbol
        if n < training_len:
            d = transmitted_symbols[n]  # Training mode
        elif n < training_len + dd_start_offset:
            d = transmitted_symbols[n]  # Extended supervised mode
        else:
            d = qpsk_decision(y)  # Decision-directed mode

        # Error
        e = d - y
        error_mse[n] = np.abs(e)**2

        # RLS update (only feedforward)
        Pi_x = np.dot(P_f, x_f)
        k = Pi_x / (lam + np.dot(x_f.conj().T, Pi_x))
        P_f = (P_f - np.outer(k, Pi_x.conj().T)) / lam
        w_f += k * e.conj()

        # Feedback filter update (LMS style)
        w_b += mu_b * e.conj() * x_b

        # Additional tracking for time-varying channels
        if n > training_len:
            # Small random perturbation to help track variations
            w_f += channel_variation_factor * np.random.randn(Nf) * (1 + 1j)
            w_b += channel_variation_factor * np.random.randn(Nb) * (1 + 1j)

        # Store filter weights for analysis
        w_f_history[n] = w_f
        w_b_history[n] = w_b

        # Symbol decision for feedback
        detected[n] = qpsk_decision(y)

    return y_out, detected, error_mse, w_f_history, w_b_history

# Function to apply time-varying channel
def apply_time_varying_channel(signal, channel_taps):
    output = np.zeros(len(signal), dtype=complex)
    num_taps = channel_taps.shape[1]

    for n in range(len(signal)):
        for k in range(num_taps):
            if n - k >= 0:
                output[n] += channel_taps[n, k] * signal[n - k]

    return output

def adding_noise(faded_signal, snr_db):
    signal_power = np.mean(np.abs(faded_signal)**2)
    snr_linear = 10**(snr_db / 10)
    noise_power = signal_power / snr_linear
    noise = np.sqrt(noise_power / 2) * (np.random.randn(len(faded_signal)) + 1j*np.random.randn(len(faded_signal)))
    rx_signal = faded_signal + noise
    return rx_signal,noise_power,signal_power

# Timing alignment or channel response	(Cross-correlation)
def correlation(signal1, signal2):
    return np.correlate(signal1, signal2, mode='full')


def compute_delay(corr, sps):
    best_delay = np.argmax(corr) - len(upsampled) + 1
    aligned_delay = best_delay + (sps - best_delay % sps) % sps
    return aligned_delay,best_delay

def recieved(signal, rrc):
    return np.convolve(signal, rrc , mode='full')

# Simulation function for time-varying channels
def simulate_time_varying_channel(channel_name, channel_taps, snr_db, tx_signal, rrc,
                                 upsampled, qpsk_symbols, Nf, Nb, delta, lam, mu_b,
                                 training_len, dd_start_offset, total_len):
    # Apply time-varying channel
    faded_signal = apply_time_varying_channel(tx_signal, channel_taps)

    # Add noise
    rx_signal,noise_power,signal_power = adding_noise(faded_signal, snr_db)


    # Matched filter
    rx_filtered = recieved(rx_signal, rrc)

    # Symbol timing (using correlation)
    corr = correlation(rx_filtered,upsampled)
    aligned_delay,best_delay = compute_delay(corr, sps)


    symbols_rx = rx_filtered[aligned_delay::sps]
    symbols_rx = symbols_rx[:len(qpsk_symbols)]
    min_len = min(len(symbols_rx), len(qpsk_symbols))

    symbols_rx = symbols_rx[:len(qpsk_symbols)]


    if snr_db == my_snr:
        print(f"{channel_name} Noise Power: {noise_power}")
        print(f"{channel_name} Signal Power: {signal_power}")
        print(f"{channel_name} Best Delay: {best_delay}")

        plt.figure(figsize=(6, 6))
        plt.scatter(np.real(symbols_rx), np.imag(symbols_rx), color='blue', alpha=0.4, s=10)
        plt.title("Received Symbols Before Equalization")
        plt.xlabel("In-phase")
        plt.ylabel("Quadrature")
        plt.axis('equal')
        plt.grid(True)
        plt.show()



    # Equalization
    rx_symbols_used = symbols_rx[:total_len]
    tx_symbols_used = qpsk_symbols[:total_len]

    y_out, detected, error_mse, w_f_hist, w_b_hist = rls_dfe_time_varying(
        rx_symbols_used, tx_symbols_used, Nf, Nb, delta, lam, mu_b,
        training_len, dd_start_offset)

    return y_out, detected, error_mse, tx_symbols_used, w_f_hist, w_b_hist

# Evaluation function for time-varying channels
def evaluate_time_varying_channels(snr_db_range, tx_signal, rrc, upsampled, qpsk_symbols,
                                  Nf, Nb, delta, lam, mu_b, training_len, dd_start_offset):

    total_len = training_len + testing_len

    # Create our two time-varying channels
    tv_channel1 = time_varying_channel_1(channel_length)
    tv_channel2 = time_varying_channel_2(channel_length)
    tv_channel3 = jakes_fading_channel(channel_length)

    channels = {
        'TV1': tv_channel1,
        'TV2': tv_channel2,
        'TV3': tv_channel3,
    }

    ber_results = {ch: [] for ch in channels}
    mse_results = {ch: [] for ch in channels}

    for snr_db in snr_db_range:
        for ch_name, channel_taps in channels.items():
            y_out, detected, error_mse, tx_symbols_used, w_f_hist, w_b_hist = simulate_time_varying_channel(
                ch_name, channel_taps, snr_db, tx_signal, rrc, upsampled, qpsk_symbols,
                Nf, Nb, delta, lam, mu_b, training_len, dd_start_offset, total_len)

            # Plot results at our target SNR
            if snr_db == my_snr:
                # Constellation plot
                plt.figure(figsize=(6, 6))
                plt.scatter(np.real(y_out), np.imag(y_out),
                           color='blue', alpha=0.4, s=10)
                plt.title(f"Equalized Constellation\n{ch_name} at {snr_db} dB")
                plt.xlabel("In-phase")
                plt.ylabel("Quadrature")
                plt.axis('equal')
                plt.grid(True)
                plt.show()

                # MSE convergence plot
                plt.figure(figsize=(8, 3))
                plt.plot((error_mse))
                plt.title(f"MSE Convergence\n{ch_name} at {snr_db} dB")
                plt.xlabel("Symbol Index")
                plt.ylabel("MSE (dB)")
                plt.grid(True)
                plt.show()

                # Filter weights evolution (show first few taps)
                plt.figure(figsize=(10, 6))
                for i in range(min(3, Nf)):
                    plt.plot(np.abs(w_f_hist[training_len:, i]),label=f'Feedforward Tap {i+1}')
                plt.title(f"Feedforward Filter Weights Evolution\n{ch_name} at {snr_db} dB")
                plt.xlabel("Symbol Index")
                plt.ylabel("Tap Magnitude")
                plt.legend()
                plt.grid(True)
                plt.show()

            # Calculate BER
            rx_bits = qpsk_to_bits(detected[training_len:])
            tx_bits = qpsk_to_bits(tx_symbols_used[training_len:])
            min_len = min(len(rx_bits), len(tx_bits))
            ber = np.mean(rx_bits[:min_len] != tx_bits[:min_len])

            if snr_db == my_snr:
                print(f"{ch_name} recieved bits: {rx_bits[:50]}")
                print(f"{ch_name} transmitted bits: {tx_bits[:50]}")
                print(f"{ch_name} BER: {ber}")


            ber_results[ch_name].append(ber)

            # Store final MSE
            final_mse = np.mean(error_mse[-1000:])  # Average last 1000 samples
            mse_results[ch_name].append(final_mse)

    return ber_results, mse_results

# Run simulation
ber_results, mse_results = evaluate_time_varying_channels(
    snr_db_range, tx_signal, rrc, upsampled, qpsk_symbols,
    Nf, Nb, delta, lam, mu_b,
    training_len, dd_start_offset
)

# Plot BER vs SNR
plt.figure(figsize=(8, 6))
for ch, ber_vals in ber_results.items():
    plt.semilogy(snr_db_range, ber_vals, marker='o', label=ch)
plt.grid(True, which='both')
plt.title("BER Performance in Time-Varying Channels")
plt.xlabel("SNR (dB)")
plt.ylabel("Bit Error Rate (BER)")
plt.legend()
plt.tight_layout()
plt.show()

# Plot MSE vs SNR
# plt.figure(figsize=(8, 6))
# for ch, mse_vals in mse_results.items():
#     plt.plot(snr_db_range, 10*np.log10(mse_vals), marker='o', label=ch)
# plt.grid(True)
# plt.title("Final MSE Performance in Time-Varying Channels")
# plt.xlabel("SNR (dB)")
# plt.ylabel("Final MSE (dB)")
# plt.legend()
# plt.tight_layout()
# plt.show()

